"use client";
import React, { useEffect, useState } from 'react';

type Answer = {
  id: number;
  textFromPdf?: string | null; // Optional: Answer extracted from the PDF
  textFromAi: string; // Required: Answer generated by AI
  isAiGenerated?: boolean; // Indicates if answer was generated by AI vs from original PDF
  isVerified?: boolean; // Indicates if answer was verified by AI
  verificationNote?: string | null; // AI verification note
  aiSuggestedAnswer?: string | null; // AI-suggested alternative answer
};

type Question = {
  id: number;
  number: number;
  part: string | null;
  text: string;
  type: string;
  image: string[];
  pageNumber?: number | null;
  options: string[];
  answers: Answer[];
};

type Exam = {
  id: number;
  url: string;
  name: string;
  subject: string;
  createdAt: string;
  parsed: boolean;
  questions: Question[];
};

type ExamViewerProps = {
  examId: number;
};

type UserAnswer = {
  questionId: number;
  answer: string;
};

type ChatMessage = {
  role: 'user' | 'assistant';
  content: string;
};

export default function ExamViewer({ examId }: ExamViewerProps) {
  const [exam, setExam] = useState<Exam | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [parsing, setParsing] = useState(false);
  const [parseError, setParseError] = useState<string | null>(null);
  const [parseProgress, setParseProgress] = useState(0);
  const [parseMessage, setParseMessage] = useState('');
  const [userAnswers, setUserAnswers] = useState<Map<number, string>>(new Map());
  const [checkedQuestions, setCheckedQuestions] = useState<Set<number>>(new Set());
  const [showImages, setShowImages] = useState<Map<number, boolean>>(new Map());
  const [showAiAnswers, setShowAiAnswers] = useState<Map<number, boolean>>(new Map());
  
  // Chatbot state
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([
    { role: 'assistant', content: 'Hello! I\'m your AI study assistant. I can help you understand the questions and concepts in this exam. Feel free to ask me anything about the questions, topics, or solutions!' }
  ]);
  const [chatInput, setChatInput] = useState('');
  const [chatLoading, setChatLoading] = useState(false);
  const [showChat, setShowChat] = useState(true);
  const [chatModel, setChatModel] = useState<'gpt' | 'claude'>('gpt');

  const toggleImage = (questionId: number) => {
    setShowImages(prev => {
      const newMap = new Map(prev);
      newMap.set(questionId, !newMap.get(questionId));
      return newMap;
    });
  };

  const toggleAiAnswer = (questionId: number) => {
    setShowAiAnswers(prev => {
      const newMap = new Map(prev);
      newMap.set(questionId, !newMap.get(questionId));
      return newMap;
    });
  };

  useEffect(() => {
    let mounted = true;

    async function fetchExam() {
      try {
        setLoading(true);
        const res = await fetch(`/api/exams/${examId}`);
        if (!res.ok) {
          throw new Error(res.status === 404 ? 'Exam not found' : 'Failed to fetch exam');
        }
        const data = await res.json();
        if (mounted) {
          // Sort questions by number and part
          const sortedQuestions = [...(data.questions || [])].sort((a, b) => {
            if (a.number !== b.number) {
              return a.number - b.number;
            }
            // If numbers are equal, sort by part (null comes first)
            if (a.part === null) return -1;
            if (b.part === null) return 1;
            return a.part.localeCompare(b.part);
          });
          setExam({ ...data, questions: sortedQuestions });
          setError(null);
          
          // Auto-parse if exam hasn't been parsed yet
          if (!data.parsed) {
            console.log('Exam not parsed, starting auto-parse...');
            handleParseExam();
          }
        }
      } catch (err: any) {
        console.error('Failed to load exam', err);
        if (mounted) setError(err?.message || 'Unknown error');
      } finally {
        if (mounted) setLoading(false);
      }
    }

    fetchExam();

    return () => {
      mounted = false;
    };
  }, [examId]);

  const handleParseExam = async () => {
    try {
      setParsing(true);
      setParseError(null);
      setParseProgress(0);
      setParseMessage('Starting...');
      
      // Use EventSource for SSE
      const eventSource = new EventSource(`/api/exams/${examId}/parse/stream`);
      
      eventSource.onmessage = (event) => {
        try {
          const data = JSON.parse(event.data);
          
          if (data.type === 'start') {
            setParseMessage(data.message);
          } else if (data.type === 'progress') {
            setParseProgress(data.progress);
            setParseMessage(data.message);
          } else if (data.type === 'complete') {
            setParseProgress(100);
            setParseMessage('Complete!');
            eventSource.close();
            
            // Refetch exam after successful parsing
            fetch(`/api/exams/${examId}`)
              .then(res => res.json())
              .then(data => {
                const sortedQuestions = [...(data.questions || [])].sort((a, b) => {
                  if (a.number !== b.number) {
                    return a.number - b.number;
                  }
                  if (a.part === null) return -1;
                  if (b.part === null) return 1;
                  return a.part.localeCompare(b.part);
                });
                setExam({ ...data, questions: sortedQuestions });
                setParsing(false);
              })
              .catch(err => {
                console.error('Failed to fetch parsed exam', err);
                setParseError('Parsing completed but failed to load exam');
                setParsing(false);
              });
          } else if (data.type === 'error') {
            setParseError(data.message);
            eventSource.close();
            setParsing(false);
          }
        } catch (err) {
          console.error('Failed to parse SSE message', err);
        }
      };
      
      eventSource.onerror = (error) => {
        console.error('SSE error:', error);
        setParseError('Connection error during parsing');
        eventSource.close();
        setParsing(false);
      };
      
    } catch (err: any) {
      console.error('Failed to start parsing', err);
      setParseError(err?.message || 'Unknown error');
      setParsing(false);
    }
  };

  const handleAnswerChange = (questionId: number, answer: string) => {
    setUserAnswers(prev => {
      const newAnswers = new Map(prev);
      newAnswers.set(questionId, answer);
      return newAnswers;
    });
  };



  const handleCheckAnswer = (questionId: number) => {
    setCheckedQuestions(prev => {
      const newChecked = new Set(prev);
      newChecked.add(questionId);
      return newChecked;
    });
  };

  const getCorrectAnswer = (question: Question): Answer | null => {
    if (question.answers && question.answers.length > 0) {
      return question.answers[0];
    }
    return null;
  };

  const isAnswerCorrect = (question: Question, userAnswer: string): boolean => {
    const correctAnswerObj = getCorrectAnswer(question);
    if (!correctAnswerObj) return false;
    const correctText = correctAnswerObj.textFromPdf || correctAnswerObj.textFromAi;
    return userAnswer.trim().toLowerCase() === correctText.trim().toLowerCase();
  };

  const getQuestionLabel = (question: Question): string => {
    return question.part ? `${question.number}${question.part}` : `${question.number}`;
  };

  const handleChatSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!chatInput.trim() || chatLoading || !exam) return;
    
    const userMessage = chatInput.trim();
    setChatInput('');
    setChatMessages(prev => [...prev, { role: 'user', content: userMessage }]);
    setChatLoading(true);
    
    try {
      // Create context from exam questions and answers
      const examContext = exam.questions.map(q => {
        const answer = getCorrectAnswer(q);
        return `Q${getQuestionLabel(q)}: ${q.text}\n${q.options.length > 0 ? 'Options: ' + q.options.join(', ') + '\n' : ''}${answer ? 'Answer: ' + (answer.textFromPdf || answer.textFromAi) : ''}`;
      }).join('\n\n');
      
      const response = await fetch('/api/exams/' + examId + '/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: userMessage,
          examContext: examContext,
          conversationHistory: chatMessages.slice(-5), // Last 5 messages for context
          model: chatModel, // Pass selected model
        })
      });
      
      if (!response.ok) {
        throw new Error('Failed to get response from AI');
      }
      
      const data = await response.json();
      setChatMessages(prev => [...prev, { role: 'assistant', content: data.response }]);
      
    } catch (error) {
      console.error('Chat error:', error);
      setChatMessages(prev => [...prev, {
        role: 'assistant',
        content: 'Sorry, I encountered an error. Please try again.'
      }]);
    } finally {
      setChatLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center p-8">
        <div className="text-lg text-gray-600">Loading exam...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-8">
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
          <p className="font-bold">Error</p>
          <p>{error}</p>
        </div>
      </div>
    );
  }

  if (!exam) {
    return (
      <div className="p-8">
        <div className="text-gray-600">No exam found.</div>
      </div>
    );
  }

  // Show parsing UI if exam hasn't been parsed yet
  if (!exam.parsed) {
    return (
      <div className="max-w-4xl mx-auto p-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2 text-black">{exam.name}</h1>
        </div>

        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
          <h2 className="text-xl font-semibold mb-3 text-blue-900 flex items-center gap-2">
            <svg className="animate-spin h-6 w-6 text-blue-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            Processing PDF...
          </h2>
          <p className="text-blue-800 mb-4">
            Analyzing exam pages and extracting questions using AI Vision.
          </p>
          <p className="text-sm text-blue-700 mb-6">
            ⏱️ This typically takes 30-60 seconds depending on exam length.
          </p>
          
          {parseError && (
            <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-lg">
              <p className="text-red-800 font-semibold mb-1">Error:</p>
              <p className="text-red-700">{parseError}</p>
            </div>
          )}

          {parsing && (
            <div className="p-4 bg-white border border-blue-200 rounded-lg">
              <div className="mb-2 flex justify-between items-center">
                <span className="text-sm font-medium text-blue-900">{parseMessage}</span>
                <span className="text-sm font-semibold text-blue-700">{parseProgress}%</span>
              </div>
              <div className="w-full bg-blue-100 rounded-full h-3 overflow-hidden">
                <div 
                  className="bg-blue-600 h-full rounded-full transition-all duration-300 ease-out"
                  style={{ width: `${parseProgress}%` }}
                ></div>
              </div>
            </div>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="flex gap-6 p-8 max-w-[1800px] mx-auto">
      {/* Main Exam Content */}
      <div className="flex-1 max-w-4xl">
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2 text-black">{exam.name}</h1>
          <div className="text-gray-600">
            <span className="font-semibold">Subject:</span> {exam.subject}
          </div>
          <div className="text-gray-500 text-sm mt-1">
            {exam.questions.length} question{exam.questions.length !== 1 ? 's' : ''}
          </div>
        </div>

        <div className="space-y-8">
        {exam.questions.map((question, index) => (
          <div
            key={question.id}
            className="bg-white border border-gray-200 rounded-lg p-6 shadow-sm"
          >
            <div className="flex items-start gap-3 mb-4">
              <div className="flex-shrink-0 w-12 h-12 bg-blue-100 text-blue-700 rounded-full flex items-center justify-center font-bold">
                {getQuestionLabel(question)}
              </div>
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-xs font-semibold px-2 py-1 bg-gray-100 text-gray-700 rounded">
                    {question.type}
                  </span>
                </div>
                <p className="text-gray-800 text-lg">{question.text}</p>
                {question.image && question.image.length > 0 && (
                  <div className="mt-3">
                    <button
                      onClick={() => toggleImage(question.id)}
                      className="mb-2 px-3 py-1.5 text-sm bg-blue-50 text-blue-600 rounded hover:bg-blue-100 transition-colors flex items-center gap-1"
                      type="button"
                    >
                      {showImages.get(question.id) ? '📷 Hide' : '📷 Show'} {question.image.length > 1 ? `Images (${question.image.length})` : 'Image'}
                    </button>
                    {showImages.get(question.id) && (
                      <div className="space-y-2">
                        {question.image.map((imgPath: string, imgIdx: number) => (
                          <img
                            key={imgIdx}
                            src={imgPath}
                            alt={`Question ${getQuestionLabel(question)} diagram ${imgIdx + 1}`}
                            className="max-w-full h-auto rounded border border-gray-300"
                          />
                        ))}
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>

            <div className="ml-15 mt-4">
              {question.type === 'MCQ' && question.options.length > 0 ? (
                <div className="space-y-2">
                  {question.options.map((option, optionIndex) => {
                    const isChecked = checkedQuestions.has(question.id);
                    const userAnswer = userAnswers.get(question.id);
                    const correctAnswerObj = getCorrectAnswer(question);
                    const isSelected = userAnswer === option;
                    const correctText = correctAnswerObj ? (correctAnswerObj.textFromPdf || correctAnswerObj.textFromAi) : '';
                    const isCorrectOption = correctText === option;
                    
                    let optionClasses = "flex items-center gap-3 p-3 rounded border transition-colors";
                    
                    if (isChecked) {
                      if (isCorrectOption) {
                        optionClasses += " bg-green-100 border-green-500";
                      } else if (isSelected && !isCorrectOption) {
                        optionClasses += " bg-red-100 border-red-500";
                      } else {
                        optionClasses += " border-gray-200";
                      }
                    } else {
                      optionClasses += " border-gray-200 hover:bg-gray-50 cursor-pointer";
                    }
                    
                    return (
                      <label
                        key={optionIndex}
                        className={optionClasses}
                      >
                        <input
                          type="radio"
                          name={`question-${question.id}`}
                          value={option}
                          checked={isSelected}
                          onChange={(e) => handleAnswerChange(question.id, e.target.value)}
                          disabled={isChecked}
                          className="w-4 h-4 text-blue-600"
                        />
                        <span className="text-gray-700 flex-1">{option}</span>
                        {isChecked && isCorrectOption && (
                          <div className="flex items-center gap-2">
                            <span className="text-green-700 font-semibold text-sm">✓ Correct</span>
                            {correctAnswerObj?.isAiGenerated && (
                              <span className="text-orange-600 font-semibold text-xs bg-orange-100 px-2 py-0.5 rounded-full" title="This answer was suggested by AI">
                                🤖 AI
                              </span>
                            )}
                            {correctAnswerObj && correctAnswerObj.isVerified === false && correctAnswerObj.verificationNote && (
                              <span className="text-red-600 font-semibold text-xs bg-red-100 px-2 py-0.5 rounded-full" title={correctAnswerObj.verificationNote}>
                                ⚠️ May Be Incorrect
                              </span>
                            )}
                            {correctAnswerObj && correctAnswerObj.isVerified === true && (
                              <span className="text-green-600 font-semibold text-xs bg-green-100 px-2 py-0.5 rounded-full">
                                ✓ Verified
                              </span>
                            )}
                          </div>
                        )}
                        {isChecked && isSelected && !isCorrectOption && (
                          <span className="text-red-700 font-semibold text-sm">✗ Wrong</span>
                        )}
                      </label>
                    );
                  })}
                  {/* AI Answer Toggle for MCQ */}
                  {checkedQuestions.has(question.id) && getCorrectAnswer(question) && !getCorrectAnswer(question)!.isAiGenerated && getCorrectAnswer(question)!.aiSuggestedAnswer && (
                    <div className="mt-3">
                      <button
                        type="button"
                        onClick={() => toggleAiAnswer(question.id)}
                        className="text-sm px-3 py-1.5 bg-purple-50 hover:bg-purple-100 text-purple-700 rounded border border-purple-200 transition-colors flex items-center gap-1"
                      >
                        {showAiAnswers.get(question.id) ? '🙈 Hide' : '🤖 View'} AI Answer
                      </button>
                      
                      {showAiAnswers.get(question.id) && (
                        <div className="mt-2 p-3 bg-purple-50 border border-purple-200 rounded-lg">
                          <div className="flex items-center gap-2 mb-1">
                            <p className="text-sm font-semibold text-purple-900">AI-Generated Answer:</p>
                            <span className="text-purple-600 font-semibold text-xs bg-purple-100 px-2 py-0.5 rounded-full">
                              🤖 Independent AI Solution
                            </span>
                          </div>
                          <div 
                            className="text-purple-800" 
                            dangerouslySetInnerHTML={{ 
                              __html: (getCorrectAnswer(question)!.aiSuggestedAnswer || '')
                                .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                                .replace(/<u>(.*?)<\/u>/g, '<u>$1</u>')
                            }} 
                          />
                          <p className="text-purple-700 text-xs mt-2 italic">
                            {getCorrectAnswer(question)!.isVerified === false 
                              ? 'This AI answer differs from the PDF answer, which may be incorrect.'
                              : 'This AI answer matches the PDF answer for your reference.'}
                          </p>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              ) : (
                <>
                  <textarea
                    value={userAnswers.get(question.id) || ''}
                    onChange={(e) => handleAnswerChange(question.id, e.target.value)}
                    placeholder="Type your answer here..."
                    disabled={checkedQuestions.has(question.id)}
                    className="w-full min-h-32 p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-y text-black disabled:bg-gray-50"
                    data-testid={`answer-input-${question.id}`}
                  />
                  {checkedQuestions.has(question.id) && getCorrectAnswer(question) && (
                    <>
                      <div className="mt-3 p-3 bg-blue-50 border border-blue-200 rounded-lg">
                        <div className="flex items-center gap-2 mb-1">
                          <p className="text-sm font-semibold text-blue-900">Correct Answer:</p>
                          {getCorrectAnswer(question)?.isAiGenerated && (
                            <span className="text-orange-600 font-semibold text-xs bg-orange-100 px-2 py-0.5 rounded-full" title="This answer was suggested by AI">
                              🤖 AI Suggested
                            </span>
                          )}
                          {getCorrectAnswer(question) && getCorrectAnswer(question)!.isVerified === false && getCorrectAnswer(question)!.verificationNote && (
                            <span className="text-red-600 font-semibold text-xs bg-red-100 px-2 py-0.5 rounded-full" title={getCorrectAnswer(question)!.verificationNote || ''}>
                              ⚠️ May Be Incorrect
                            </span>
                          )}
                          {getCorrectAnswer(question) && getCorrectAnswer(question)!.isVerified === true && (
                            <span className="text-green-600 font-semibold text-xs bg-green-100 px-2 py-0.5 rounded-full">
                              ✓ Verified
                            </span>
                          )}
                        </div>
                        {getCorrectAnswer(question)?.isAiGenerated ? (
                          <div 
                            className="text-blue-800" 
                            dangerouslySetInnerHTML={{ 
                              __html: (getCorrectAnswer(question)?.textFromAi || '')
                                .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                                .replace(/<u>(.*?)<\/u>/g, '<u>$1</u>')
                            }} 
                          />
                        ) : (
                          <p className="text-blue-800">{getCorrectAnswer(question)?.textFromPdf || getCorrectAnswer(question)?.textFromAi}</p>
                        )}
                        {getCorrectAnswer(question)?.isAiGenerated && (
                          <p className="text-orange-700 text-xs mt-2 italic">
                            Note: This answer was generated by AI as no answer was provided in the original document.
                          </p>
                        )}
                        {getCorrectAnswer(question) && getCorrectAnswer(question)!.isVerified === false && getCorrectAnswer(question)!.verificationNote && (
                          <p className="text-red-700 text-xs mt-2 italic">
                            ⚠️ Warning: {getCorrectAnswer(question)!.verificationNote}
                          </p>
                        )}
                      </div>
                      {/* AI Answer Toggle - Show for ALL questions with AI answer */}
                      {getCorrectAnswer(question) && !getCorrectAnswer(question)!.isAiGenerated && getCorrectAnswer(question)!.aiSuggestedAnswer && (
                        <div className="mt-2">
                          <button
                            type="button"
                            onClick={() => toggleAiAnswer(question.id)}
                            className="text-sm px-3 py-1.5 bg-purple-50 hover:bg-purple-100 text-purple-700 rounded border border-purple-200 transition-colors flex items-center gap-1"
                          >
                            {showAiAnswers.get(question.id) ? '🙈 Hide' : '🤖 View'} AI Answer
                          </button>
                          
                          {showAiAnswers.get(question.id) && (
                            <div className="mt-2 p-3 bg-purple-50 border border-purple-200 rounded-lg">
                              <div className="flex items-center gap-2 mb-1">
                                <p className="text-sm font-semibold text-purple-900">AI-Generated Answer:</p>
                                <span className="text-purple-600 font-semibold text-xs bg-purple-100 px-2 py-0.5 rounded-full">
                                  🤖 Independent AI Solution
                                </span>
                              </div>
                              <div 
                                className="text-purple-800" 
                                dangerouslySetInnerHTML={{ 
                                  __html: (getCorrectAnswer(question)!.aiSuggestedAnswer || '')
                                    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                                    .replace(/<u>(.*?)<\/u>/g, '<u>$1</u>')
                                }} 
                              />
                              <p className="text-purple-700 text-xs mt-2 italic">
                                {getCorrectAnswer(question)!.isVerified === false 
                                  ? 'This AI answer differs from the PDF answer, which may be incorrect.'
                                  : 'This AI answer matches the PDF answer for your reference.'}
                              </p>
                            </div>
                          )}
                        </div>
                      )}
                    </>
                  )}
                </>
              )}
            </div>
            
            {!checkedQuestions.has(question.id) && (
              <div className="ml-15 mt-4">
                <button
                  type="button"
                  onClick={() => handleCheckAnswer(question.id)}
                  disabled={!userAnswers.has(question.id)}
                  className="px-4 py-2 bg-purple-600 text-white font-semibold rounded-lg hover:bg-purple-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
                  data-testid={`check-answer-${question.id}`}
                >
                  Check Answer
                </button>
              </div>
            )}
          </div>
        ))}
        </div>
      </div>

      {/* AI Chatbot Panel */}
      {showChat && (
        <div className="w-96 flex flex-col bg-white border border-gray-300 rounded-lg shadow-lg sticky top-8 h-[calc(100vh-4rem)]">
          <div className="p-4 border-b border-gray-200 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-t-lg">
            <div className="flex justify-between items-start mb-2">
              <div>
                <h2 className="text-lg font-bold">🤖 AI Study Assistant</h2>
                <p className="text-xs opacity-90">Ask me about the exam!</p>
              </div>
              <button
                onClick={() => setShowChat(false)}
                className="text-white hover:bg-white/20 rounded px-2 py-1 transition-colors"
              >
                ✕
              </button>
            </div>
            <div className="flex items-center gap-2">
              <label htmlFor="model-select" className="text-xs opacity-90 whitespace-nowrap">
                Model:
              </label>
              <select
                id="model-select"
                value={chatModel}
                onChange={(e) => setChatModel(e.target.value as 'gpt' | 'claude')}
                className="flex-1 px-2 py-1 text-xs bg-white/20 border border-white/30 rounded text-white backdrop-blur-sm focus:outline-none focus:ring-2 focus:ring-white/50"
              >
                <option value="gpt" className="text-gray-900">GPT-4o Mini</option>
                <option value="claude" className="text-gray-900">Claude 3.5 Sonnet</option>
              </select>
            </div>
          </div>
          
          <div className="flex-1 overflow-y-auto p-4 space-y-4">
            {chatMessages.map((msg, idx) => (
              <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                <div className={`max-w-[80%] rounded-lg p-3 ${
                  msg.role === 'user' 
                    ? 'bg-blue-500 text-white' 
                    : 'bg-gray-100 text-gray-800'
                }`}>
                  <div className="text-sm whitespace-pre-wrap" dangerouslySetInnerHTML={{ __html: msg.content.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/<u>(.*?)<\/u>/g, '<u>$1</u>') }} />
                </div>
              </div>
            ))}
            {chatLoading && (
              <div className="flex justify-start">
                <div className="bg-gray-100 rounded-lg p-3">
                  <div className="text-sm text-gray-600">Thinking...</div>
                </div>
              </div>
            )}
          </div>
          
          <form onSubmit={handleChatSubmit} className="p-4 border-t border-gray-200">
            <div className="flex gap-2">
              <input
                type="text"
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                placeholder="Ask a question..."
                disabled={chatLoading}
                className="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-black disabled:bg-gray-100"
              />
              <button
                type="submit"
                disabled={chatLoading || !chatInput.trim()}
                className="px-4 py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors"
              >
                Send
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Toggle Chat Button (when hidden) */}
      {!showChat && (
        <button
          onClick={() => setShowChat(true)}
          className="fixed right-8 bottom-8 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-full p-4 shadow-lg hover:shadow-xl transition-shadow"
        >
          <span className="text-2xl">💬</span>
        </button>
      )}
    </div>
  );
}
